# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('code', models.FileField(upload_to=b'')),
                ('date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
